services:
  postgres:
    image: postgres:16-alpine
    container_name: sistem-pix-postgres
    environment:
      POSTGRES_DB: sistem_pix
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: